repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uvx ruff@0.3.1 check .
        args: [--fix]
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uvx ruff@0.3.1 format .
        language: system
        types: [python]
