version: "3"
tasks:
  check:
    desc: Run pre-commit checks
    cmds:
      - uvx ruff@0.3.1 check . --fix
      - uvx ruff@0.3.1 format .
      # - uvx mypy@1.8.0 . --strict

  run:
    desc: Run the application
    cmds:
      - uv run -m src.my_project

  test:
    desc: Run tests
    cmds:
      - uv run pytest
